### ISSUE TITLE
Unable to connect HTML page to PHp 

### ISSUE THREAD

**Issue by manishkarki2022** [manishkarki2022/E-Challan#3]

**Comment by Madhur-Bist** [comment]
Discuss with other developers about this issue.

**Comment by uchia77** [comment]
this can be closed by connecting to database with the help of xamp

**Comment by uchia77** [comment]
link through which learned to fix problems 
https://youtu.be/2HVKizgcfjo

**Comment by PukarKatwal88** [comment]
https://www.youtube.com/watch?v=J7pnxQtUdgM

**Comment by PukarKatwal88** [comment]
Check this link . I hope this issue will be solved 
https://www.youtube.com/watch?v=J7pnxQtUdgM
