### ISSUE TITLE
Traffic and admin login issue

### ISSUE THREAD

**Issue by AnujJaiswal03** [manishkarki2022/E-Challan#6]
Traffic login and admin login didn't satisfy project manager so he said to change all the login page
![login ss](https://user-images.githubusercontent.com/101965669/167287852-b0936ebb-b026-4fc1-ae93-e4409b8de35a.png)

**Comment by manishkarki2022** [comment]
![Screenshot 2022-05-14 225542](https://user-images.githubusercontent.com/96905327/168441830-429a5ce8-147d-4dab-adf3-7f5eb2279ad6.png)
AS per the client request new login page for the admin and traffic

**Comment by uchia77** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="secondpage.css">
    <title>E-CHALLAN SYSTEM</title>
</head>


<body>
    <h1 id="heading">E-CHALLAN SYSTEM</h1>
    
        <div class="box-one">

        </div>
        <div class="box-two">

        </div>
    </div>
    <h2>Login</h2>
             <div class="login-wrapper"> 
               
                 
                    <div class="input-group">
                    <p>Are you a Admin?</p>

                    </div>
                     <div class="input">
                       
                   <p> Are you a Traffic?</p>

                    </div> 
                   
                    <a href="" class="alink"><input type="submit" value="Admin" class="submit-btn"></a>
                    <a href="" class="blink"> <input type="submit" value="Traffic" class="submit"></a>
                
                


  
    </div>

</body>

</html>

**Comment by uchia77** [comment]
updated code for the final decsion page

**Comment by uchia77** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="secondpage.css">
    <title>E-CHALLAN SYSTEM</title>
</head>


<body>
    <h1 id="heading">E-CHALLAN SYSTEM</h1>
    
        <div class="box-one">

        </div>
        <div class="box-two">

        </div>
    </div>
    <h2>Login</h2>
             <div class="login-wrapper"> 
               
                 
                    <div class="input-group">
                    <p>Are you a Admin?</p>

                    </div>
                     <div class="input">
                       
                   <p> Are you a Traffic?</p>

                    </div> 
                   
                    <a href="" class="alink"><input type="submit" value="Admin" class="submit-btn"></a>
                    <a href="" class="blink"> <input type="submit" value="Traffic" class="submit"></a>
                
                


  
    </div>

</body>

</html>

**Comment by AnujJaiswal03** [comment]
This issue has been solved
