### ISSUE TITLE
 TRAFFIC PAGE ISSUES

### ISSUE THREAD

**Issue by PukarKatwal88** [manishkarki2022/E-Challan#7]
Due to improper format of traffic page I had to change some of the traffic page 
![Screen Shot 2022-05-08 at 2 11 41 PM](https://user-images.githubusercontent.com/101967703/167288074-d00cbff7-3a46-420b-a414-e669d19cecad.png)

**Comment by manishkarki2022** [comment]
![Screenshot 2022-05-13 164422](https://user-images.githubusercontent.com/96905327/168269934-ecaac83c-b210-42e3-a1bc-97f68df1381c.png)
This is the new updated page  of Traffic Dashboard
